import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import { Inter } from "next/font/google";
import { cn } from "@/app/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl" className={cn("font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">{children}
        <Footer />
      </body>
    </html>
  );
}
